# Generated by Django 5.2 on 2025-09-10 12:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmbienteSena', '0002_alter_instructor_cedula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHoraEntrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('fechaHoraSalida', models.DateTimeField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AmbienteSena.ambiente')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AmbienteSena.instructor')),
            ],
            options={
                'db_table': 'ingreso',
            },
        ),
    ]
